"""empty message

Revision ID: 78578223304d
Revises: 8dfe97bc577d
Create Date: 2017-03-03 16:27:20.338379

"""

# revision identifiers, used by Alembic.
revision = '78578223304d'
down_revision = '8dfe97bc577d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'branches', ['name'])
    op.create_unique_constraint(None, 'branches', ['port'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'branches', type_='unique')
    op.drop_constraint(None, 'branches', type_='unique')
    # ### end Alembic commands ###
