"""empty message

Revision ID: 8dfe97bc577d
Revises: 7a8dfaecbda6
Create Date: 2017-03-03 10:15:22.623356

"""

# revision identifiers, used by Alembic.
revision = '8dfe97bc577d'
down_revision = '7a8dfaecbda6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('container_id', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'container_id')
    # ### end Alembic commands ###
