"""empty message

Revision ID: 1f0f67a8fdfe
Revises: 8dfe97bc577d
Create Date: 2017-09-26 14:37:55.044113

"""

# revision identifiers, used by Alembic.
revision = '1f0f67a8fdfe'
down_revision = '8dfe97bc577d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('aliases', sa.String(length=100), nullable=True))
    op.add_column('branches', sa.Column('config', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'config')
    op.drop_column('branches', 'aliases')
    # ### end Alembic commands ###
