"""empty message

Revision ID: 7a8dfaecbda6
Revises: 46b6431c891f
Create Date: 2017-03-02 14:04:34.254648

"""

# revision identifiers, used by Alembic.
revision = '7a8dfaecbda6'
down_revision = '46b6431c891f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('branches', sa.Column('port', sa.Integer(), nullable=True))
    op.add_column('branches', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'status')
    op.drop_column('branches', 'port')
    op.drop_column('branches', 'created')
    # ### end Alembic commands ###
